# Generated by Django 2.2.3 on 2020-03-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreaverage',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scorerecord',
            name='scored_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
