# Generated by Django 2.2.3 on 2020-03-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_auto_20200326_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scorerecord',
            options={'ordering': ['-scored_time'], 'verbose_name_plural': '评分记录'},
        ),
        migrations.AlterField(
            model_name='scorerecord',
            name='scored_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
