# Generated by Django 2.2.3 on 2020-03-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_auto_20200326_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorerecord',
            name='scored_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
