# Generated by Django 2.2.3 on 2020-04-25 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0005_auto_20200420_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreaverage',
            name='average',
            field=models.FloatField(max_length=2, verbose_name='平均分'),
        ),
        migrations.AlterField(
            model_name='scoreaverage',
            name='count',
            field=models.IntegerField(default=0, verbose_name='评分条数'),
        ),
        migrations.AlterField(
            model_name='scorerecord',
            name='scored_num',
            field=models.PositiveIntegerField(default=0, verbose_name='分数'),
        ),
        migrations.AlterField(
            model_name='scorerecord',
            name='scored_time',
            field=models.DateField(auto_now_add=True, verbose_name='评分时间'),
        ),
        migrations.AlterField(
            model_name='scorerecord',
            name='text',
            field=models.CharField(max_length=100, verbose_name='评价内容'),
        ),
        migrations.AlterField(
            model_name='scorerecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评价用户'),
        ),
    ]
