# Generated by Django 2.2.3 on 2020-04-20 08:42

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_time'], 'verbose_name': '课程', 'verbose_name_plural': '课程'},
        ),
        migrations.AlterModelOptions(
            name='articledetail',
            options={'ordering': ['created_time'], 'verbose_name': '课程内容', 'verbose_name_plural': '课程内容'},
        ),
        migrations.AlterModelOptions(
            name='articletype',
            options={'verbose_name': '课程类型', 'verbose_name_plural': '课程类型'},
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleType', verbose_name='课程类型'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='课程介绍'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='icon',
            field=models.ImageField(blank=True, default='default/课程封面.jpg', null=True, upload_to='media/uploads/article', verbose_name='课程封面'),
        ),
        migrations.AlterField(
            model_name='article',
            name='introduction',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='额外说明'),
        ),
        migrations.AlterField(
            model_name='article',
            name='last_updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=50, verbose_name='课程标题'),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='last_updated_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='num',
            field=models.PositiveIntegerField(default=1, verbose_name='课时'),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='title',
            field=models.CharField(max_length=50, verbose_name='课时标题'),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='type_name',
            field=models.CharField(max_length=15, verbose_name='课程类型'),
        ),
    ]
