# Generated by Django 2.2.3 on 2020-04-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200425_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='grade',
            field=models.CharField(choices=[('cj', '初级'), ('gj', '高级'), ('zj', '中级')], default='cj', max_length=2),
        ),
    ]
