# Generated by Django 2.2.3 on 2020-04-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='grade',
            field=models.CharField(choices=[('zj', '中级'), ('cj', '初级'), ('gj', '高级')], default='cj', max_length=2, verbose_name='难度等级'),
        ),
    ]
