# Generated by Django 2.2.3 on 2020-04-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20200425_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='grade',
            field=models.IntegerField(choices=[(1, '中级'), (2, '高级'), (0, '初级')], default=0, max_length=2, verbose_name='难度等级'),
        ),
    ]
