# Generated by Django 2.2.3 on 2020-04-10 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikesCount',
            new_name='LikeCount',
        ),
    ]
