# Generated by Django 2.2.4 on 2020-04-14 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_auto_20200410_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likecount',
            options={'verbose_name': '点赞统计', 'verbose_name_plural': '点赞统计'},
        ),
        migrations.AlterModelOptions(
            name='likerecord',
            options={'verbose_name': '点赞记录', 'verbose_name_plural': '点赞记录'},
        ),
    ]
