# Generated by Django 2.2.3 on 2020-03-14 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participatearticle',
            options={'verbose_name': '参加课程', 'verbose_name_plural': '参加课程'},
        ),
    ]
