# Generated by Django 2.2.3 on 2020-03-15 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article_statistics', '0003_auto_20200315_1025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParticipateArticle',
            new_name='ParticipateRecord',
        ),
        migrations.AlterModelOptions(
            name='participaterecord',
            options={'verbose_name': '参加记录', 'verbose_name_plural': '参加记录'},
        ),
        migrations.RenameField(
            model_name='participaterecord',
            old_name='participate_num',
            new_name='participate',
        ),
        migrations.CreateModel(
            name='ParticipateCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('participate_num', models.IntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '参加统计',
                'verbose_name_plural': '参加统计',
            },
        ),
    ]
