# Generated by Django 2.2.3 on 2020-03-11 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('icon', models.ImageField(blank=True, max_length=255, null=True, upload_to='media/usericon/')),
                ('gender', models.IntegerField(choices=[('0', '男'), ('1', '女'), ('2', '保密')], default=2)),
                ('birth', models.DateField(blank=True, null=True)),
                ('user_type', models.BooleanField(default=0)),
                ('education', models.IntegerField(default=8)),
                ('introduction', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户档案',
                'verbose_name_plural': '用户档案',
            },
        ),
    ]
