# Generated by Django 2.2.3 on 2020-03-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.IntegerField(choices=[(0, '小学'), (1, '初中'), (2, '高中'), (3, '专科'), (4, '本科'), (5, '研究生'), (6, '硕士'), (7, '博士'), (8, '其他')], default=8),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(choices=[(0, '男'), (1, '女'), (2, '保密')], default=2),
        ),
    ]
