# Generated by Django 2.2.3 on 2020-03-14 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200314_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_introduction',
            new_name='introduction',
        ),
    ]
