# Generated by Django 2.2.4 on 2020-04-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200314_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='icon',
            field=models.ImageField(blank=True, default='default/头像.svg', null=True, upload_to='media/user_avatar/%Y/%m/%d'),
        ),
    ]
