# Generated by Django 2.2.3 on 2020-04-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200414_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='icon',
            field=models.ImageField(blank=True, default='default/avatar.svg', null=True, upload_to='media/user_avatar/%Y/%m/%d'),
        ),
    ]
