# Generated by Django 2.2.3 on 2020-04-25 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200415_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.IntegerField(choices=[(0, '小学'), (1, '初中'), (2, '高中'), (3, '专科'), (4, '本科'), (5, '研究生'), (6, '硕士'), (7, '博士'), (8, '其他')], default=8, verbose_name='当前学历'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(choices=[(0, '男'), (1, '女'), (2, '保密')], default=2, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='icon',
            field=models.ImageField(blank=True, default='default/avatar.svg', null=True, upload_to='media/user_avatar/%Y/%m/%d', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='introduction',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=20, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户账号'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.BooleanField(default=False, verbose_name='用户类别'),
        ),
    ]
