# Generated by Django 2.2.3 on 2020-03-24 04:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('comment', '0002_auto_20200324_1202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Score',
            new_name='ScoreRecord',
        ),
        migrations.AlterModelOptions(
            name='scorerecord',
            options={'verbose_name_plural': '课程评分'},
        ),
    ]
