# Generated by Django 2.2.3 on 2020-03-24 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('comment', '0003_auto_20200324_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scorerecord',
            options={'verbose_name_plural': '评分记录'},
        ),
        migrations.AlterField(
            model_name='scorerecord',
            name='scored_num',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ScoreAverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('average', models.FloatField(max_length=2)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': '评分平均分',
            },
        ),
    ]
