# Generated by Django 2.2.3 on 2020-03-24 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20200324_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorerecord',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='scorerecord',
            name='user',
        ),
        migrations.DeleteModel(
            name='ScoreAverage',
        ),
        migrations.DeleteModel(
            name='ScoreRecord',
        ),
    ]
